---
- name: Exploring the template module and jinja expressions
  hosts: planetexpress
  gather_facts: no   # runs the "setup" module on remote hosts

  # these variables are used to build templates
  vars:
    instructions:
       - mission: primary
         planet: "luna park"
       - mission: secondary
         planet: "cineplex 14"


  tasks:
    - name: Configure mission orders challenge
      template:
        src: templates/mission-orders-c.txt.j2    # name of the template on ansible controller
        dest: "~/{{ item.mission }}-mission-orders.txt"              # name of the completed file to be placed on the target system
      loop: "{{ instructions }}"
